### ISSUE TITLE
Handling optional (missing) data

### ISSUE THREAD

**Issue by simonstewart** [ijoshsmith/json2swift#9]
Our 3rd party API has somewhat variable data.  Not the best API design decision, but we aren't in control of it.

Both of these are valid:
```
{
 "firstName":"Bob",
 "lastName":"Smith"
}
```
and
```
{
 "lastName":"Bob"
}
```

Json2Swift has support for eg:
```
{
 "firstName":null,
 "lastName":null
}
```
But I can't find anything related to optionals.

Any ideas baring enriching the JSON with nulls prior to code gen?

**Comment by ijoshsmith** [comment]
Hi Simon,

I believe that `json2swift` already does what you need. I created this example JSON:
```json
[
  {
    "firstName":"Bob",
    "lastName":"Smith"
  },
  {
    "lastName":"Bob"
  }
]
```
Here is the Swift code produced by the tool:
```swift
struct RootType: CreatableFromJSON { // TODO: Rename this struct
    let firstName: String?
    let lastName: String
    init(firstName: String?, lastName: String) {
        self.firstName = firstName
        self.lastName = lastName
    }
    init?(json: [String: Any]) {
        guard let lastName = json["lastName"] as? String else { return nil }
        let firstName = json["firstName"] as? String
        self.init(firstName: firstName, lastName: lastName)
    }
}
```
As you can see, the type inference logic is able to detect the optionality of `firstName`. Does this solve your problem?

**Comment by simonstewart** [comment]
Thanks @ijoshsmith.  So the tool uses a `let` when the field appeared at least once and `guard let` when it appeared in all objects?

**Comment by simonstewart** [comment]
@ijoshsmith is there a way to indicate to the tool which fields are optional (i.e. may not be there, so should be nullable in Swift), without having to have multiple documents in an array?

Our input is a Swagger doc.  The JSON that each call outputs is just an example and obviously doesn't have any schema attached.

**Comment by simonstewart** [comment]
Another example is if a single JSON element exists with eg:
```
  {
    "firstName":"Bob",
    "lastName":"Smith"
  }
```
Where firstName is optional.  If it's within an array, I can do what you recommended, but any ideas for single objects?

**Comment by ijoshsmith** [comment]
Regarding your question about `let` versus `guard let`, the former is used for optional values since the initializer can proceed when an optional value is missing. The `guard let` is needed for required values, since the initializer must return `nil` (i.e. fail) if a required value is missing.

Regarding your question about indicating which fields are optional, that can be accomplished by providing multiple examples of the same JSON element in an array. Perhaps one that has all of the elements, and another that indicates which of them can be null, like this:
```
[
  {
    "firstName":"Bob",
    "lastName":"Smith"
  },
  {
    "firstName":null,
    "lastName":null
  }
]
```
This JSON would result in `json2swift` creating a struct with two optional properties.

This obviously doesn't meet your needs regarding "any ideas for single objects" but that's not something I can work around. This tool infers the schema of whatever JSON you present to it, so it's limited by the information found in the data provided to it. It sounds like what you're getting at is a tool that converts a JSON Schema to Swift code, which would be a different tool.

**Comment by simonstewart** [comment]
@ijoshsmith appreciate the feedback, thank you.
